name: Release Flatpak Bundle

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# Default deny all token permissions
permissions: {}

jobs:
  release:
    name: Build & Release Flatpak Bundle
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build Flatpak Package
        uses: flatpak/flatpak-github-actions/flatpak-builder@fc80c13788c1ba0f45add99b19cf26b616ccab4f # v6.4
        with:
          bundle: io.filen.desktop.flatpak
          manifest-path: io.filen.desktop.yaml
          arch: x86_64
          run-tests: false

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: io.filen.desktop.flatpak
          draft: false
          prerelease: false
          generate_release_notes: true
