name: Release Flatpak Bundle

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# Default deny all token permissions
permissions: {}

jobs:
  release:
    name: Build & Release Flatpak Bundle
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Trust Workspace Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build Flatpak & Create Bundle
        run: bash scripts/build/build-flatpak.sh
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish GitHub Release
        run: bash scripts/build/publish-release.sh io.filen.desktop.flatpak
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
